
import Navbar from "@/components/navbar/Navbar"
import Footer from "@/components/footer/Footer"
import { Inter, Nunito } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const nunito = Nunito({ subsets: ["latin"] ,weight:["400","500","800"]})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body >
        <Navbar />
        <main className={inter.className}>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}


