import Navbar from "@/components/navbar/Navbar"
import Footer from "@/components/footer/Footer"
import { Inter, Nunito } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const nunito = Nunito({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
"use client"

  return (
    <html lang="en">
      <body className={nunito.className}>
        <main>
          <Navbar />
          <article>
          {children}
          </article>
          <Footer />
        </main>
      </body>
    </html>
  );
}
